### ISSUE TITLE
which npm package ? What is @bytemain/openai-fetch ?

### ISSUE THREAD

**Issue by 0gust1** [dexaai/openai-fetch#14]
Wanted to run API calls from edge, and had to find fetch-based client. 

Stumbled upon this repo, but when searching npmjs.org, I found 2 packages pointing to this repo: `openai-fetch` and `@bytemain/openai-fetch`. Found this a bit strange/questioning.

**Comment by rileytomasek** [comment]
It looks like `@bytemain` forked this repo and published the fork to npm, presumably to avoid paying for private packages. You're safe to ignore it and use `openai-fetch` because it will continue to get updates from this repo.
