### ISSUE TITLE
Please can you elaborate more on this phrase in readme?

### ISSUE THREAD

**Issue by gutkedu** [dexaai/openai-fetch#19]
Please can you elaborate more on this phrase in readme? 

`Unfortunately, the official [openai-node](https://github.com/openai/openai-node) uses Axios, which only supports Node and is bloated.`

 I got curious why you say that the axios and nodejs client is "bloated"

**Comment by rileytomasek** [comment]
Also from the readme:
> Package size: openai-fetch is [~5kb](https://bundlephobia.com/package/openai-fetch) and openai-node is [~180kb](https://bundlephobia.com/package/openai-node)
