### ISSUE TITLE
Add support for fine tune model apis

### ISSUE THREAD

**Issue by NachoVazquez** [dexaai/openai-fetch#29]
Currently, the library doesn't support any interaction with fine tunings.

The following is a list of wanted methods to be included:

- `retrieveFineTune`
- `listFineTunes`
- `createFineTune`
- `cancelFineTune`
- `listFineTuneEvents`

Thanks for your efforts.

**Comment by rileytomasek** [comment]
I'm open to PRs, but I don't see a ton of value in adding these since you'd normally be running them from an environment that the official OpenAI package supports.
