### ISSUE TITLE
add option to pass fetch lib as argument

### ISSUE THREAD

**Issue by dominiksipowicz** [dexaai/openai-fetch#6]
Is it possible to extend API configuration to pass a specific fetch library? 

It might solve some issues related to the different hosting environments.

something like that:
```
const client = new OpenAIClient({ apiKey: '<your api key>', fetch: myFetch });
```

**Comment by transitive-bullshit** [comment]
Another option for library authors to consider w/ `fetch` is to assume that `fetch` exists in the environment as `ky` does.

If that's not the case, then have the user of the lib polyfill `fetch`.

Here's a timely article on this I came across yesterday https://www.builder.io/blog/stop-polyfilling-fetch-in-your-npm-package

@dominiksipowicz are you seeing any specific issues in hosting environments, or is this more about general best practices?

**Comment by transitive-bullshit** [comment]
I've run into similar `ky` issues before w/ a lib I maintain. I *love* `ky` and it's syntax, especially intelligent retries based on error code, but I have a feeling that maybe allowing the user to override `fetch` as @dominiksipowicz suggested and defaulting to native `fetch` may be a simpler solution.

**Comment by dominiksipowicz** [comment]
> defaulting to native fetch may be a simpler solution.

Yes, this is what I wanted to say initially thank you @transitive-bullshit

**Comment by dominiksipowicz** [comment]
@transitive-bullshit 

> are you seeing any specific issues in hosting environments, or is this more about general best practices?

- hosting on the edge issues
- overall size
- best practice

**Comment by rileytomasek** [comment]
I'm considering allowing you to pass a fetch implementation to Ky (see #4), but that will be fetch controlled by Ky.

**Comment by rileytomasek** [comment]
#9 allows passing fetch options. Beyond that, this library is going to assume global fetch exists and will be left to the user to polyfill if needed.
