### ISSUE TITLE
Add streaming support

### ISSUE THREAD

**Issue by transitive-bullshit** [dexaai/openai-fetch#7]
Opening an issue to track this feature, since it seems to keep coming up, and I'm expecting to make use of it soon for a project.

See also:
- https://www.beskar.co/blog/streaming-openai-completions-vercel-edge
- https://www.npmjs.com/package/@beskar-labs/parse-json-sse
- https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/fetch-sse.ts

**Comment by rileytomasek** [comment]
Streaming would be great. Do you know if it's possible with Ky?

**Comment by dglazkov** [comment]
@transitive-bullshit if you'd like, try the patch I submitted for review.
